name: test github actions

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: first-step in workflow
        run: echo "First print"
      - name: second-step in workflow
        run: echo "Second print"
