name: test github actions

on:
  push:
    branches:
      - branch1
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: shr-1
    #container:
    #  image: node:lts-alpine3.18
    steps:
      #- name: check node version
      #  run: node --version
      - name: Print github predefined variables
        run: |
          echo hello
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF