name: test github actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: shr-1
    #container:
    #  image: node:lts-alpine3.18
    steps:
      #- name: check node version
      #  run: node --version
      - name: Hello
        run: echo hello
