name: test github actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine3.18
    steps:
      - name: check node version
        run: node --version
